Chore/webpack 5 upgrade
merkle-open/env-linter pull request #27
Opened 2022-11-21 07:33 UTC by malinovic

Hi, this merge request contains following updates:

- remove node 12 support
- update dev dependencies to a newer version (important: webpack)

If there are any open questions, please get back to me as soon as possible :)

Best regards,
Danijel

2022-11-22 09:08 UTC, ernscht requested changes

2022-11-22 09:08 UTC, ernscht commented on webpack.config.js
>  		libraryTarget: 'umd',
'libraryTarget' and 'umdNamedDefine' are deprecated in webpack 5

2022-11-22 09:08 UTC, ernscht commented on package.json
>      "ts-config-webpack-plugin": "2.0.3",
this config plugin is webpack 4 only

we should configure webpack 5 without this plugin

2023-01-09 10:43 UTC, malinovic commented
Resolved in other pull request.

2023-01-09 10:43 UTC, closed without merging